name: Build and Deploy Dynamic App

on:
  push:
    branches:
      - master
    paths:
      - 'web-dinamis/**'
      - 'docker-compose.yml'
      - '.github/workflows/deploy.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./web-dinamis
          file: ./web-dinamis/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/web-dinamis-uas:latest

  deploy-to-aws:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      # PENTING: Mengambil ulang semua file repositori ke workspace runner ini
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Memastikan file docker-compose.yml benar-benar ada sebelum di-SCP
      - name: Verify Compose File Exists
        run: |
          if [ -f "docker-compose.yml" ]; then
            echo "File docker-compose.yml ditemukan!"
          else
            echo "ERROR: File docker-compose.yml tidak ada di root folder!" && exit 1
          fi

      - name: Copy docker-compose via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          source: "docker-compose.yml" # Mengambil file compose dari root
          target: "/home/${{ secrets.AWS_USERNAME }}/" # Target spesifik ke home dir user AWS

      - name: Executing remote SSH commands to deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            export DOCKERHUB_USERNAME="${{ secrets.DOCKERHUB_USERNAME }}"
            
            # Login Docker Hub di EC2
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
            
            # Masuk ke direktori tempat file compose berada
            cd /home/${{ secrets.AWS_USERNAME }}
            
            # Pull & Up kontainer
            docker compose pull
            docker compose up -d --remove-orphans